using System;

namespace Notary.Data.Main_Core.Model
{
    public class transaction_additional_data
    {
        public int Id { get; set; }
        public int transaction_common_data_id { get; set; }
        public string TT2_piece_description { get; set; }
        public string TT2_province_description { get; set; }
        public string TT3_purpose { get; set; }
        public string TT5_vehicle_number { get; set; }
        public string TT5_vehicle_type { get; set; }
        public string TT5_vehicle_year_number { get; set; }
        public string TT5_vehicle_color { get; set; }
        public Nullable<int> TT5_vehicle_manufact_year { get; set; }
        public Nullable<int> TT5_vehicle_passenger_count { get; set; }
        public string TT5_vehicle_cargo { get; set; }
        public string TT5_vehicle_engine_number { get; set; }
        public string TT5_vehicle_shase_number { get; set; }
        public string TT5_vehicle_owner_name { get; set; }
        public string TT5_vehicle_holder_name { get; set; }
        public Nullable<double> TT6_amount { get; set; }
        public string TT6_attendance_at { get; set; }
        public string TT6_attendance_for { get; set; }
        public string TT6_payment_safe { get; set; }
        public Nullable<double> TT7_amount { get; set; }
        public string TT7_court_name { get; set; }
        public string TT7_court_case_number { get; set; }
        public string TT8_partner_name { get; set; }
        public string TT9_student_name { get; set; }
        public string TT9_donor { get; set; }
        public string TT9_certificate_name { get; set; }
        public string TT10_martyr_name { get; set; }
        public Nullable<System.DateTime> TT10_martyr_date { get; set; }
        public string TT12_transaction_description { get; set; }
        public string TT12_transaction_conditions { get; set; }
        public string TT13_confession { get; set; }
        public string TT16_chapter1 { get; set; }
        public string TT16_chapter2 { get; set; }
        public string TT16_period { get; set; }
        public string TT19_current_record_count { get; set; }
        public Nullable<System.DateTime> TT19_current_record_date { get; set; }
        public string TT19_current_record_lather { get; set; }
        public string TT19_from_record_count { get; set; }
        public Nullable<System.DateTime> TT19_from_record_date { get; set; }
        public string TT19_from_record_lather { get; set; }
        public string TT19_to_record_count { get; set; }
        public Nullable<System.DateTime> TT19_to_record_date { get; set; }
        public string TT19_to_record_lather { get; set; }
        public string TT19_judgement { get; set; }
        public Nullable<int> TT19_district_id { get; set; }
        public string TT19_building { get; set; }
        public string TT19_piece { get; set; }
        public string TT19_province { get; set; }
        public string TT19_owner_name { get; set; }
        public string TT19_factory_name { get; set; }
        public string TT19_mortgage_from { get; set; }
        public string TT19_mortgage_to { get; set; }
        public string TT19_mortgage_type { get; set; }
        public Nullable<double> TT19_mortgage_amount { get; set; }
        public Nullable<System.DateTime> TT19_mortgage_start_date { get; set; }
        public Nullable<System.DateTime> TT19_mortgage_end_date { get; set; }
        public string TT19_mortgage_other { get; set; }
        public Nullable<System.DateTime> TT19_mortgage_over_date { get; set; }
        public string TT19_machine_type { get; set; }
        public string TT19_machine_specifications { get; set; }
        public string TT19_machine_origin { get; set; }
        public string TT19_machine_fuel_type { get; set; }
        public string TT19_machine_horse_power { get; set; }
        public string TT19_machine_volume { get; set; }
        public string TT19_machine_class { get; set; }
        public string TT19_machine_purpose { get; set; }
        public string TT19_machine_information { get; set; }
        public string TT19_machine_purchase { get; set; }
        public Nullable<double> TT19_machine_value { get; set; }
        public string TT19_current_actions { get; set; }
        public Nullable<int> TT19_governorate_id { get; set; }
        public Nullable<int> TT20_governorate_id { get; set; }
        public string TT20_judgement { get; set; }
        public Nullable<int> TT20_district_id { get; set; }
        public string TT20_building { get; set; }
        public string TT20_piece { get; set; }
        public string TT20_province { get; set; }
        public string TT20_owner_name { get; set; }
        public string TT20_factory_name { get; set; }
        public string TT20_edbara_number { get; set; }
        public string TT20_mortgage_from { get; set; }
        public string TT20_mortgage_to { get; set; }
        public string TT20_mortgage_type { get; set; }
        public Nullable<double> TT20_mortgage_amount { get; set; }
        public Nullable<System.DateTime> TT20_mortgage_start_date { get; set; }
        public Nullable<System.DateTime> TT20_mortgage_end_date { get; set; }
        public string TT20_record_lether { get; set; }
        public Nullable<double> TT20_survey_wage { get; set; }
        public string TT20_survey_employee { get; set; }
        public string TT20_survey_expert { get; set; }
        public Nullable<System.DateTime> TT20_survey_date { get; set; }
        public string TT20_current_actions { get; set; }
        public string TT21_Edbara_number { get; set; }
        public Nullable<int> TT21_current_record_count { get; set; }
        public Nullable<System.DateTime> TT21_current_record_date { get; set; }
        public string TT21_current_record_lather { get; set; }
        public Nullable<int> TT21_from_record_count { get; set; }
        public Nullable<System.DateTime> TT21_from_record_date { get; set; }
        public string TT21_from_record_lather { get; set; }
        public Nullable<int> TT21_to_record_count { get; set; }
        public Nullable<System.DateTime> TT21_to_record_date { get; set; }
        public string TT21_to_record_lather { get; set; }
        public Nullable<int> TT21_governorate_id { get; set; }
        public string TT21_judgement { get; set; }
        public Nullable<int> TT21_district_id { get; set; }
        public string TT21_building { get; set; }
        public string TT21_piece { get; set; }
        public string TT21_province { get; set; }
        public string TT21_owner_name { get; set; }
        public string TT21_factory_name { get; set; }
        public string TT21_mortgage_from { get; set; }
        public string TT21_mortgage_to { get; set; }
        public string TT21_mortgage_type { get; set; }
        public Nullable<double> TT21_mortgage_amount { get; set; }
        public Nullable<System.DateTime> TT21_mortgage_start_date { get; set; }
        public Nullable<System.DateTime> TT21_mortgage_end_date { get; set; }
        public string TT21_mortgage_other { get; set; }
        public Nullable<System.DateTime> TT21_mortgage_over_date { get; set; }
        public string TT21_machine_type { get; set; }
        public string TT21_machine_specifications { get; set; }
        public string TT21_machine_origin { get; set; }
        public string TT21_machine_fuel_type { get; set; }
        public string TT21_machine_horse_power { get; set; }
        public string TT21_machine_volume { get; set; }
        public string TT21_machine_class { get; set; }
        public string TT21_machine_purpose { get; set; }
        public string TT21_machine_information { get; set; }
        public string TT21_machine_purchase { get; set; }
        public Nullable<double> TT21_machine_value { get; set; }
        public string TT21_current_actions { get; set; }
        public string TT23_recorded1 { get; set; }
        public Nullable<System.DateTime> TT23_recorded1_date { get; set; }
        public string TT23_recorded2 { get; set; }
        public Nullable<double> TT24_amount { get; set; }
        public string TT24_amount_text { get; set; }
        public string TT24_amount_reason { get; set; }
        public Nullable<System.DateTime> TT25_due_date { get; set; }
        public Nullable<double> TT25_amount { get; set; }
        public string TT25_amount_text { get; set; }
        public string TT25_amount_reason { get; set; }
        public string TT29_warning_description { get; set; }
        public string TT30_warning_description { get; set; }
        public string TT33_warning_description { get; set; }
        public string TT34_warning_Number { get; set; }
        public Nullable<System.DateTime> TT34_warning_Date { get; set; }
        public string TT34_warning_description { get; set; }
        public Nullable<System.DateTime> TT34_intimation_date { get; set; }
        public string TT34_intimation_name { get; set; }
        public string TT31_previous_JW { get; set; }
        public string TT31_previous_transaction_number { get; set; }
        public Nullable<System.DateTime> TT31_previous_date { get; set; }
        public Nullable<int> TT31_previous_record_number { get; set; }
        public string TT36_previous_JW_office { get; set; }
        public Nullable<int> TT36_previous_public_number { get; set; }
        public Nullable<System.DateTime> TT36_previous_date { get; set; }
        public Nullable<int> TT36_previous_record_number { get; set; }
        public string TT36_warning_description { get; set; }
        public Nullable<double> TT16_contact_value { get; set; }
        public string TT19_contract_deccription { get; set; }
        public string TT19_contract_confitions { get; set; }
        public Nullable<double> TT19_contact_value { get; set; }
        public Nullable<int> TT26_PagesCount { get; set; }
        public Nullable<int> TT27_source_trans_public_nuber { get; set; }
        public string TT36_transaction_number { get; set; }
        public string TT38_association_type { get; set; }
        public string TT38_record_number { get; set; }
        public string TT38_record_number_owner { get; set; }
        public string TT40_association_transaction_number { get; set; }
        public Nullable<int> TT27_PagesCount { get; set; }
        public string TT29_warning_acting { get; set; }
        public string TT29_warning_notification_to { get; set; }
        public string TT31_warning_acting { get; set; }
        public string TT31_warning_notification_to { get; set; }
        public string TT33_transaction_number { get; set; }
        public string TT33_warning_acting { get; set; }
        public string TT33_warning_notification_to { get; set; }
        public string TT30_real_Estate_number { get; set; }
        public Nullable<int> TT30_district_id { get; set; }
        public Nullable<double> TT30_rent_value { get; set; }
        public string TT30_warning_acting { get; set; }
        public string TT30_warning_notification_to { get; set; }
        public Nullable<bool> TT30_Secretariats { get; set; }
        public Nullable<bool> TT29_print_warning_notification { get; set; }
        public Nullable<bool> TT29_print_warning_notification_book { get; set; }
        public Nullable<bool> TT30_print_warning_notification { get; set; }
        public Nullable<bool> TT30_print_warning_notification_book { get; set; }
        public Nullable<bool> TT31_print_warning_notification { get; set; }
        public Nullable<bool> TT31_print_warning_notification_book { get; set; }
        public Nullable<bool> TT33_print_warning_notification { get; set; }
        public Nullable<bool> TT33_print_warning_notification_book { get; set; }
        public Nullable<double> TT43_amount { get; set; }
        public string TT43_attendance_at { get; set; }
        public string TT43_attendance_for { get; set; }
        public string TT43_payment_safe { get; set; }
        public string TT15_contract_deccription { get; set; }
        public string TT15_contract_confitions { get; set; }
        public Nullable<double> TT15_contract_value { get; set; }
        public string TT14_contract_deccription { get; set; }
        public string TT14_contract_confitions { get; set; }
        public Nullable<bool> TT14_is_contract_withvalue { get; set; }
        public Nullable<double> TT14_contract_value { get; set; }
        public string TT17_contract_deccription { get; set; }
        public string TT17_contract_confitions { get; set; }
        public Nullable<bool> TT17_is_contract_withvalue { get; set; }
        public Nullable<double> TT17_contract_value { get; set; }
        public string TT18_contract_deccription { get; set; }
        public string TT18_contract_confitions { get; set; }
        public Nullable<bool> TT18_is_contract_withvalue { get; set; }
        public Nullable<double> TT18_contract_value { get; set; }
        public string TT32_previous_JW { get; set; }
        public string TT32_previous_transaction_number { get; set; }
        public Nullable<System.DateTime> TT32_previous_date { get; set; }
        public Nullable<int> TT32_previous_record_number { get; set; }
        public string TT32_warning_acting { get; set; }
        public string TT32_warning_notification_to { get; set; }
        public Nullable<bool> TT32_print_warning_notification { get; set; }
        public Nullable<bool> TT32_print_warning_notification_book { get; set; }
        public string TT44_contract_deccription { get; set; }
        public string TT44_contract_confitions { get; set; }
        public Nullable<double> TT44_contract_value { get; set; }
        public string TT41_request_type { get; set; }
        public string TT41_nameof_almukhtas_visit { get; set; }
        public string TT41_placefor_almukhtas { get; set; }
        public string TT41_resonfor_visit { get; set; }
        public string TT41_machine_description { get; set; }
        public string TT41_placefor_machine { get; set; }

        public virtual transaction_common_data transaction_common_data { get; set; }
    }
}